"""Display titles for the RBT front-end.

Centralizes the user-facing book title overrides so templates and views
can import from a single location.
"""

rbt_books: dict[str, str] = {
    'Genesis': 'In the Head',
    'Exodus': 'And a Mighty One of Names',
    'Leviticus': 'And He is Summoning',
    'Numbers': 'And He is Aligning',
    'Deuteronomy': 'A Mighty One of the Alignments',
    'Joshua': 'He Is Salvation',
    'Judges': 'Judges',
    'Ruth': 'Companion',
    '1 Samuel': 'First Name of God',
    '2 Samuel': 'Second Name of God',
    '1 Kings': 'First Kings',
    '2 Kings': 'Second Kings',
    '1 Chronicles': 'First Alignments of the Days',
    '2 Chronicles': 'Second Alignments of the Days',
    'Ezra': 'Helper',
    'Nehemiah': 'He Is Comforted',
    'Esther': 'Star',
    'Job': 'Adversary',
    'Psalms': 'Melodies',
    'Proverbs': 'Comparisons',
    'Ecclesiastes': 'Alignments of the Teacher',
    'Song of Solomon': 'The Song of Singers',
    'Isaiah': 'He Is Liberator',
    'Jeremiah': 'He Is Lifting Up',
    'Lamentations': 'How She Sat Desolate!',
    'Ezekiel': 'God Holds Strongly',
    'Daniel': 'God Has Judged',
    'Hosea': 'Salvation',
    'Joel': 'Being God',
    'Amos': 'Heavy Burdened',
    'Obadiah': 'Slave of He Is',
    'Jonah': 'Dove',
    'Micah': 'Who is Like Her?',
    'Nahum': 'Consolation',
    'Habakkuk': 'Embrace-Embrace',
    'Zephaniah': 'He Is Concealed',
    'Haggai': 'Festival',
    'Zechariah': 'He Is Remembered',
    'Malachi': 'Angel of Myself',
    'Matthew': 'He Is a Gift',
    'Mark': 'Hammer',
    'Luke': 'Light Giver',
    'John': 'He Is Favored',
    'Acts': 'Acts of the Sent Away Ones',
    'Romans': 'People of Bodily Strength',
    '1 Corinthians': 'First People of Youth',
    '2 Corinthians': 'Second People of Youth',
    'Galatians': 'People of the Land of Milk',
    'Ephesians': 'People of the Land of Bees',
    'Philippians': 'People of the Horse',
    'Colossians': 'People of the Colossal Ones',
    '1 Thessalonians': 'First People of Prayer Victory',
    '2 Thessalonians': 'Second People of Prayer Victory',
    '1 Timothy': 'First Honored One',
    '2 Timothy': 'Second Honored One',
    'Titus': 'Avenged',
    'Philemon': 'The Kisser',
    'Hebrews': 'Beyond Ones',
    'James': 'Heel Chaser',
    '1 Peter': 'First Stone',
    '2 Peter': 'Second Stone',
    '1 John': 'First Favored',
    '2 John': 'Second Favored',
    '3 John': 'Third Favored',
    'Jude': 'Praised One',
    'Revelation': 'The Unveiling',
}
