# Generated by Django 5.0.4 on 2024-07-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationUpdates',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('version', models.TextField()),
                ('reference', models.TextField()),
                ('update_text', models.TextField()),
            ],
            options={
                'db_table': 'translation_updates',
            },
        ),
        migrations.AddField(
            model_name='genesis',
            name='rbt_reader',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
