# Generated by Django 5.0.4 on 2025-09-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_translationupdates_genesis_rbt_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englxx',
            name='verseID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
