# Generated by Django 5.0.4 on 2026-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_versetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='versetranslation',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='versetranslation',
            name='generated_by',
            field=models.CharField(default='gemini-3-flash-preview', max_length=50),
        ),
    ]
