# Generated by Django 5.0.4 on 2026-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_versetranslation_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versetranslation',
            name='book_name',
        ),
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('job_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_verses', models.IntegerField(default=0)),
                ('translated_verses', models.IntegerField(default=0)),
                ('total_footnotes', models.IntegerField(default=0)),
                ('translated_footnotes', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translation_jobs',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_job_status')],
            },
        ),
    ]
