# Generated by Django 5.0.4 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_add_interlinearconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlinearApplyLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('committed', models.BooleanField(default=False)),
                ('total_candidates', models.IntegerField(default=0)),
                ('applied_count', models.IntegerField(default=0)),
                ('sample', models.TextField(blank=True, null=True)),
                ('backup_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interlinear_apply_log',
                'ordering': ['-applied_at'],
            },
        ),
    ]
