# Generated by Django 5.0.4 on 2026-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_interlinearapplylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'visitor_locations',
                'indexes': [models.Index(fields=['timestamp', 'is_bot'], name='visitor_loc_timesta_07cd67_idx')],
            },
        ),
    ]
