# Generated by Django 5.0.4 on 2026-04-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_aeon_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key_abbrev', models.CharField(max_length=20)),
                ('request_type', models.CharField(max_length=50)),
                ('language_code', models.CharField(max_length=10)),
                ('book', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gemini_usage_logs',
            },
        ),
    ]
