# Generated by Django 5.0.4 on 2026-09-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_geminiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('sense', models.TextField(help_text='What the phrase actually means here.')),
                ('use_guidance', models.TextField(help_text='What to use, e.g. "the target language\'s ordinary word for \'ratio\'".')),
                ('avoid', models.TextField(blank=True, default='', help_text='Wordings that would be wrong.')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_glossary_terms',
                'ordering': ['order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='PromptRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('chapter', 'Chapter prompt only'), ('footnote', 'Footnote prompt only'), ('both', 'Both prompts')], default='chapter', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Sort order within its prompt.')),
                ('text', models.TextField(help_text='The instruction as sent, without its number.')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_rules',
                'ordering': ['scope', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromptLanguageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('rendering', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='search.promptglossaryterm')),
            ],
            options={
                'db_table': 'prompt_language_overrides',
                'ordering': ['language_code'],
                'unique_together': {('term', 'language_code')},
            },
        ),
    ]
