# Generated by Django 5.0.4 on 2026-09-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_seed_prompt_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versetranslation',
            name='generated_by',
            field=models.CharField(default='gemini-3.8-flash', max_length=50),
        ),
    ]
