# Generated by Django 5.0.4 on 2026-09-30 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_versetranslation_source_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaphrasePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField()),
                ('word_guidance', models.TextField(blank=True, default='', help_text='Paraphrase-specific word/usage notes, one per line.')),
                ('include_glossary', models.BooleanField(default=True, help_text='Also include the active translation glossary terms.')),
                ('is_default', models.BooleanField(default=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paraphrase_prompts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterParaphrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_id', models.UUIDField(db_index=True, help_text='Generations started together, for side-by-side comparison.')),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('html', models.TextField(blank=True, default='', help_text='Sanitised reader HTML with media placeholders resolved.')),
                ('raw_output', models.TextField(blank=True, default='', help_text='Model output exactly as returned.')),
                ('missing_verses', models.JSONField(blank=True, default=list)),
                ('prompt_name', models.CharField(blank=True, default='', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Full system prompt as sent.')),
                ('source_hash', models.CharField(blank=True, default='', help_text="Hash of the chapter's verse text when generated.", max_length=64)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('thinking_tokens', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chapter_paraphrases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', 'chapter', 'language_code'], name='chapter_paraphrase_ref_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chapterparaphrase',
            constraint=models.UniqueConstraint(condition=models.Q(('is_published', True)), fields=('book', 'chapter', 'language_code'), name='one_published_paraphrase_per_chapter'),
        ),
    ]
